from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'games'

urlpatterns = [
    path(
        '',
        views.home,
        name='home'
    ),
    path(
        'register/',
        views.GameRegisterView.as_view(),
        name='register'
    ),
    path(
        'login/',
        views.GameLoginView.as_view(),
        name='login',),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout',
    ),
    path(
      'password-change/',
        views.GamePasswordChangeView.as_view(),
        name='change_password',
    ),
    path(
        'password-change/done/',
        views.GamePasswordChangeDoneView.as_view(),
        name='change_password_done',
    ),
    path(
        'password-reset/',
        views.GamePasswordResetView.as_view(),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        views.GamePasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password-reset/confirm/<uidb64>/<token>/',
        views.GamePasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'password-reset/complete/',
        views.GamePasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
    path(
        'profile/',
        views.GameProfileView.as_view(),
        name='profile',
    ),
    path(
        'profile/edit/',
        views.GameProfileUpdateView.as_view(),
        name='profile_edit',
    ),
    path(
        'games/',
        views.GameListView.as_view(),
        name='game_list'
    ),
    path(
        'ratings/',
        views.ratings,
        name='ratings'),
    path(
        'games/add/',
        views.GameCreateView.as_view(),
        name='game_create'),
    path(
        'games/latest/',
        views.latest_game,
        name='latest_game'),
    path(
        'games/year/<int:release_year>/',
        views.games_by_year,
        name='games_by_year'),
    path(
        'games/<slug:game_slug>/',
        views.GameDetailView.as_view(),
        name='game_detail',
    ),
    path(
        'games/<slug:game_slug>/edit/',
        views.GameUpdateView.as_view(),
        name='game_edit',
    ),
    path(
        'games/<slug:game_slug>/delete/',
        views.GameDeleteView.as_view(),
        name='game_delete',
    ),

]