# Generated by Django 6.0.7 on 2026-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_developer_game_genre_game_platform_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('planned', 'Хочу пройти'), ('playing', 'Прохожу'), ('completed', 'Пройдено')], default='planned', max_length=20),
        ),
    ]
