# Generated by Django 6.0.7 on 2026-07-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_cover_game_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-release_year', 'title'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='playtime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
