# Generated by Django 6.0.7 on 2026-07-22 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options_game_playtime_game_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
