# Generated by Django 6.0.7 on 2026-07-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_game_rating_between_1_and_10'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='games.game')),
            ],
            options={
                'verbose_name': 'Особенность игры',
                'verbose_name_plural': 'Особенности игры',
                'ordering': ['position', 'id'],
            },
        ),
    ]
