# Generated by Django 6.0.7 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gamehighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.feature'),
        ),
    ]
