# Generated by Django 6.0.7 on 2026-08-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-release_year', 'title'], 'permissions': [('manage_all_games', 'Может управлять всеми играми')], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
