# Generated by Django 6.0.7 on 2026-08-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_options'),
        ('library', '0003_migrate_game_data_to_library')
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='game_rating_between_1_and_10',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
    ]
