# Generated by Django 6.0.7 on 2026-10-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_game_game_rating_between_1_and_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upload_cover',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
